-- 1

SELECT * FROM ADDRESS
WHERE LASTNAME='BAILEY';

-- 2
SELECT * FROM BOOKSHELF
WHERE PUBLISHER='SCHOLASTIC'
AND CATEGORYNAME='CHILDRENFIC';

--3
SELECT * FROM BOOKSHELF
WHERE PUBLISHER='SCHOLASTIC'
OR PUBLISHER='HARPERCOLLINS';

--4
SELECT * FROM ADDRESS
WHERE FIRSTNAME LIKE 'W%';

--5
SELECT * FROM ADDRESS
WHERE LASTNAME IN ('BAILEY', 'CASEY', 'ZACK');

--6
SELECT TITLE, PUBLISHER, CATEGORYNAME
FROM BOOKSHELF
WHERE PUBLISHER NOT IN ('HARPERCOLLINS', 'VIKING'); 

--7
SELECT *
FROM ADDRESS
WHERE ZIP IS NOT NULL;

--8
SELECT * FROM ADDRESS
ORDER BY LASTNAME DESC;

--9
SELECT *
  FROM STOCK_ACCOUNT JOIN STOCK_TRX
    ON STOCK_ACCOUNT.ACCOUNT = STOCK_TRX.ACCOUNT
 WHERE QUANTITY='100';
 
 /*
 
These views have already been created and are currently residing in the Views folder
 
View 1 – Creating a View using at least four of the above list
CREATE VIEW view_name AS
SELECT *
FROM BOOKSHELF
WHERE PUBLISHER='HARPERCOLLINS';

View 2
CREATE VIEW VIEW_WHERE AS
SELECT * FROM ADDRESS
WHERE LASTNAME='BAILEY';

View 3
CREATE VIEW VIEW_AND AS
SELECT * FROM BOOKSHELF
WHERE PUBLISHER='SCHOLASTIC'
AND CATEGORYNAME='CHILDRENFIC';

View 4
CREATE VIEW VIEW_AND AS
SELECT * FROM ADDRESS
WHERE LASTNAME IN ('BAILEY', 'CASEY', 'ZACK');

 */