--1
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY HH24:MI:SS';
SELECT CURRENT_DATE FROM DUAL;

--2
select user from dual;

--3
SELECT ROUND(date '2018-12-25' - CURRENT_DATE) as dateDiff
from dual;

--4
SELECT to_char(CYCLEDATE, 'Month') "Month", (LAST_DAY(CYCLEDATE) - CYCLEDATE) "Days between"
   FROM PAYDAY;

--5
SELECT PERSON FROM LEDGER WHERE NOT (PERSON LIKE '%STORE'
OR PERSON LIKE '%OFFICE'
OR PERSON LIKE '%CHURCH'
OR PERSON LIKE '%HARDWARE'
OR PERSON LIKE '%AND%'
OR PERSON LIKE 'BLACKSMITH'
OR PERSON LIKE 'SCHOOL'
OR PERSON LIKE 'LIVERY'
OR PERSON LIKE '%COMPANY'
OR PERSON LIKE 'MILL');

--6
SELECT SUBSTR(PHONE,1,3) "AREA_CODE", 
COUNT(SUBSTR(PHONE,1,3)) "COUNT(*)" 
FROM ADDRESS 
GROUP BY SUBSTR(PHONE,1,3) 
HAVING COUNT(SUBSTR(PHONE,1,3))>1;

--7
SELECT RPAD(FIRSTNAME || ' ' || LASTNAME,50,'.') As FullName,
'(' || SUBSTR(PHONE,1,3) || ')' || SUBSTR(PHONE,5,12) As Phone
FROM ADDRESS
ORDER BY LASTNAME ASC, FIRSTNAME ASC;
