SELECT WORKER.NAME, WORKER.AGE, WORKER.LODGING, SKILL, ABILITY
FROM WORKERSKILL
LEFT OUTER JOIN WORKER
ON WORKERSKILL.NAME = WORKER.NAME
WHERE WORKERSKILL.ABILITY != 'GOOD'
AND WORKERSKILL.ABILITY != 'AVERAGE'
AND WORKERSKILL.ABILITY != 'EXCELLENT'
ORDER BY NAME;