SELECT DECODE(
    GROUPING(PERSON), 1, 'Total', PERSON) AS SUBTOTAL,
TO_CHAR(ACTIONDATE, 'Month') AS MONTH, SUM(QUANTITY*RATE) AS TOT_AMT
FROM LEDGER
WHERE ACTION = 'SOLD'
GROUP BY ROLLUP (PERSON, ACTIONDATE)
ORDER BY PERSON;