SELECT PERSON, SUM(AMOUNT) AS TOTAL,
COUNT(PERSON) AS COUNT
FROM LEDGER
WHERE EXISTS (SELECT * FROM WORKER
             WHERE WORKER.NAME = LEDGER.PERSON)
      AND ACTION='BOUGHT'
GROUP BY PERSON
ORDER BY PERSON;
