SELECT WORKER.NAME, WORKER.AGE, WORKER.LODGING, SKILL, ABILITY
FROM WORKERSKILL
LEFT OUTER JOIN WORKER
ON WORKERSKILL.NAME = WORKER.NAME
WHERE WORKERSKILL.ABILITY NOT IN ('GOOD', 'EXCELLENT', 'AVERAGE')
ORDER BY NAME;